# Generated by Django 4.1.3 on 2022-11-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название фильма')),
                ('director', models.CharField(max_length=25, verbose_name='Режиссер')),
            ],
        ),
    ]
