# Generated by Django 4.1.3 on 2022-12-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_film_overflew'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
