# Generated by Django 4.1.3 on 2022-12-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_film_soup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='image',
        ),
    ]
