# Generated by Django 4.1.3 on 2022-12-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_reaction_recsys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='recsys',
            field=models.IntegerField(default=None, verbose_name='Система рекомендаций'),
        ),
    ]
