# Generated by Django 4.1.3 on 2022-11-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_reaction_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='Film',
            field=models.FileField(default=None, null=True, upload_to='films/'),
        ),
    ]
