# Generated by Django 4.1.3 on 2022-11-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_film_remove_reaction_film_reaction_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='film',
            field=models.CharField(max_length=20, verbose_name='Название фильма'),
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
