# Generated by Django 4.1.3 on 2022-11-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_alter_reaction_film_delete_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название фильма')),
            ],
        ),
        migrations.AlterField(
            model_name='reaction',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.film'),
        ),
    ]
